terraform import module.app_data.aws_s3_bucket.uploads medicojobs-cluster-uploads-168614391879
terraform import "module.app_data.aws_dynamodb_table.this[\"medicojobs-reputation\"]" medicojobs-reputation
terraform import "module.app_data.aws_dynamodb_table.this[\"medicojobs-locations\"]" medicojobs-locations
terraform import "module.app_data.aws_dynamodb_table.this[\"medicojobs-users\"]" medicojobs-users
terraform import "module.app_data.aws_dynamodb_table.this[\"medicojobs-availability\"]" medicojobs-availability
terraform import "module.app_data.aws_dynamodb_table.this[\"medicojobs-resumes\"]" medicojobs-resumes
terraform import "module.app_data.aws_dynamodb_table.this[\"medicojobs-matching\"]" medicojobs-matching
terraform import "module.app_data.aws_dynamodb_table.this[\"medicojobs-jobs\"]" medicojobs-jobs
terraform import "module.app_data.aws_dynamodb_table.this[\"medicojobs-courses\"]" medicojobs-courses
terraform import module.app_data.aws_secretsmanager_secret.shared medicojobs-cluster/shared-secrets
terraform import module.eks.aws_iam_role.cluster medicojobs-cluster-cluster-role
terraform import module.eks.aws_iam_role.node medicojobs-cluster-node-role
terraform import module.github_actions_iam.aws_iam_openid_connect_provider.github_actions arn:aws:iam::168614391879:oidc-provider/token.actions.githubusercontent.com
terraform import module.github_actions_iam.aws_iam_policy.ecr_push arn:aws:iam::168614391879:policy/medicojobs-cluster-github-actions-ecr-push
terraform import module.observability.aws_cloudwatch_log_group.application /aws/eks/medicojobs-cluster/application
terraform import module.security_kms.aws_kms_alias.platform alias/medicojobs-cluster-platform
