apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medicojobs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MedicoJobs
    targetRevision: main
    path: terraform-eks/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: medicojobs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
