apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - api-gateway.yaml
  - frontend.yaml
  - user-service.yaml
  - job-service.yaml
  - matching-service.yaml
  - availability-service.yaml
  - location-service.yaml
  - reputation-service.yaml
  - course-service.yaml
  - resume-service.yaml
  - hpa-pdb.yaml
  - ingress.yaml
  - gateway.yaml
