apiVersion: v1
kind: Secret
metadata:
  name: medicojobs-secrets
  namespace: medicojobs
type: Opaque
stringData:
  JWT_SECRET: "replace-me"
  MONGO_URI_USER: "replace-me"
  MONGO_URI_JOB: "replace-me"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "replace-me"
  SMTP_PASS: "replace-me"
  SMTP_FROM: "replace-me"
  AWS_ACCESS_KEY_ID: "replace-me-if-not-using-irsa"
  AWS_SECRET_ACCESS_KEY: "replace-me-if-not-using-irsa"
